version: '3'
services:
  ldap-server:
    image: osixia/openldap:1.2.3
    ports:
      - "389:389"
      - "636:636"
    environment:
      LDAP_DOMAIN : "my-company.com"
      LDAP_ORGANISATION : "My Company"
      LDAP_ADMIN_PASSWORD : "P@ssw0rd@1"
      
  ldap-admin:
    image: osixia/phpldapadmin:0.7.2
    ports:
      - "6443:443"
    environment:
      PHPLDAPADMIN_LDAP_HOSTS=localhost

  nexus3:
    image: sonatype/nexus3
    ports:
      - "8081:8081"
    environment:
      NEXUS_CONTEXT : nexus
      
  sonarqube:
    image: sonarqube:7.5-community
    ports:
      - "9000:9000"
  jenkins:
    image: jenkins:2.60.3-alpine
    ports:
      - "8080:8080"
      - "50000:50000"
      
  gitlab:
    image: gitlab/gitlab-ce:latest
    ports:
      - "443:443"
      - "80:80"
      - "22:22"
